<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Activite_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get activite by acti_id
     */
    function get_activite($acti_id)
    {
        return $this->db->get_where('activites',array('acti_id'=>$acti_id))->row_array();
    }
    
    /*
     * Get all activites count
     */
    function get_all_activites_count()
    {
        $this->db->from('activites');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all activites
     */
    function get_all_activites($params = array())
    {
        $this->db->order_by('acti_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('activites')->result_array();
    }
        
    /*
     * function to add new activite
     */
    function add_activite($params)
    {
        $this->db->insert('activites',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update activite
     */
    function update_activite($acti_id,$params)
    {
        $this->db->where('acti_id',$acti_id);
        return $this->db->update('activites',$params);
    }
    
    /*
     * function to delete activite
     */
    function delete_activite($acti_id)
    {
        return $this->db->delete('activites',array('acti_id'=>$acti_id));
    }
}
