<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Campagne_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get campagne by camp_id
     */
    function get_campagne($camp_id)
    {
        return $this->db->get_where('campagnes',array('camp_id'=>$camp_id))->row_array();
    }
    
    /*
     * Get all campagnes count
     */
    function get_all_campagnes_count()
    {
        $this->db->from('campagnes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all campagnes
     */
    function get_all_campagnes($params = array())
    {
        $this->db->order_by('camp_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('campagnes')->result_array();
    }
        
    /*
     * function to add new campagne
     */
    function add_campagne($params)
    {
        $this->db->insert('campagnes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update campagne
     */
    function update_campagne($camp_id,$params)
    {
        $this->db->where('camp_id',$camp_id);
        return $this->db->update('campagnes',$params);
    }
    
    /*
     * function to delete campagne
     */
    function delete_campagne($camp_id)
    {
        return $this->db->delete('campagnes',array('camp_id'=>$camp_id));
    }
}
