<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Centre_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get centre by centre_id
     */
    function get_centre($centre_id)
    {
        return $this->db->get_where('centres',array('centre_id'=>$centre_id))->row_array();
    }
    
    /*
     * Get all centres count
     */
    function get_all_centres_count()
    {
        $this->db->from('centres');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all centres
     */
    function get_all_centres($params = array())
    {
        $this->db->order_by('centre_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('centres')->result_array();
    }
        
    /*
     * function to add new centre
     */
    function add_centre($params)
    {
        $this->db->insert('centres',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update centre
     */
    function update_centre($centre_id,$params)
    {
        $this->db->where('centre_id',$centre_id);
        return $this->db->update('centres',$params);
    }
    
    /*
     * function to delete centre
     */
    function delete_centre($centre_id)
    {
        return $this->db->delete('centres',array('centre_id'=>$centre_id));
    }
}
