<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vaccin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vaccin by vacc_id
     */
    function get_vaccin($vacc_id)
    {
        return $this->db->get_where('vaccins',array('vacc_id'=>$vacc_id))->row_array();
    }
    
    /*
     * Get all vaccins count
     */
    function get_all_vaccins_count()
    {
        $this->db->from('vaccins');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all vaccins
     */
    function get_all_vaccins($params = array())
    {
        $this->db->order_by('vacc_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('vaccins')->result_array();
    }
        
    /*
     * function to add new vaccin
     */
    function add_vaccin($params)
    {
        $this->db->insert('vaccins',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vaccin
     */
    function update_vaccin($vacc_id,$params)
    {
        $this->db->where('vacc_id',$vacc_id);
        return $this->db->update('vaccins',$params);
    }
    
    /*
     * function to delete vaccin
     */
    function delete_vaccin($vacc_id)
    {
        return $this->db->delete('vaccins',array('vacc_id'=>$vacc_id));
    }
}
